{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stacks
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stacks_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stacks/stacks_{{ version }}.tar.gz
  sha256: 38f11af357c230aea146616d20b0b6fc2fdeb24ba32b72b41a70a0d7a5a948c4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip      # [win]
  host:
    - r-base
    - r-butcher >=0.1.3
    - r-cli
    - r-dofuture
    - r-dplyr >=1.1.0
    - r-foreach
    - r-future
    - r-generics
    - r-ggplot2
    - r-glmnet
    - r-glue
    - r-parsnip >=1.2.0
    - r-purrr >=1.0.0
    - r-recipes >=1.0.10
    - r-rlang >=1.1.3
    - r-rsample >=1.2.0
    - r-tibble >=2.1.3
    - r-tidyr
    - r-tune >=1.2.0
    - r-vctrs >=0.6.1
    - r-workflows >=1.1.4
  run:
    - r-base
    - r-butcher >=0.1.3
    - r-cli
    - r-dofuture
    - r-dplyr >=1.1.0
    - r-foreach
    - r-future
    - r-generics
    - r-ggplot2
    - r-glmnet
    - r-glue
    - r-parsnip >=1.2.0
    - r-purrr >=1.0.0
    - r-recipes >=1.0.10
    - r-rlang >=1.1.3
    - r-rsample >=1.2.0
    - r-tibble >=2.1.3
    - r-tidyr
    - r-tune >=1.2.0
    - r-vctrs >=0.6.1
    - r-workflows >=1.1.4

test:
  commands:
    - $R -e "library('stacks')"           # [not win]
    - "\"%R%\" -e \"library('stacks')\""  # [win]

about:
  home: https://stacks.tidymodels.org/
  dev_url: https://github.com/tidymodels/stacks
  license: MIT
  summary: Model stacking is an ensemble technique that involves training a model to combine the outputs of many diverse statistical models, and has been shown to improve predictive performance in a variety of settings. 'stacks' implements a grammar for 'tidymodels'-aligned model stacking.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
